#!/usr/bin/env python

import traceback

import redis

from redisrpc import RedisRPCClient
from calc import Calculator

def do_calculations(calculator):
    calculator.clr()
    print(calculator.add(2.0))
    print(calculator.add(5.5))
    print(calculator.sub(3.1))
    print(calculator.mul(2))
    print(calculator.div(3))
    try:
        print(calculator.foo())
    except:
        traceback.print_exc()
    calculator.clr()

# Local object.
calculator = Calculator()
do_calculations(calculator)

redis_server = redis.Redis()

# Remote object.
calculator = RedisRPCClient(redis_server, 'calc')
do_calculations(calculator)

# Remote object with local run-time type checking.
calculator = RedisRPCClient(redis_server, 'calc', Calculator)
do_calculations(calculator)
