#!/usr/bin/env python

import redis

from redisrpc import RedisRPCServer
from calc import Calculator

redis_server = redis.Redis()
server = RedisRPCServer(redis_server, 'calc', Calculator())
server.run()
